// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9JCBjGIIyj1EBJrq8HJq2NdxORzmKjI',
    appId: '1:585491402759:web:7cdbfa9c26c1eb1c0cdaa2',
    messagingSenderId: '585491402759',
    projectId: 'propp-400e1',
    authDomain: 'propp-400e1.firebaseapp.com',
    databaseURL: 'https://propp-400e1-default-rtdb.firebaseio.com',
    storageBucket: 'propp-400e1.appspot.com',
    measurementId: 'G-T12NMWR863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GwUl1lyE_0-f8EaI71VX3KbfFaK1Q54',
    appId: '1:585491402759:android:f0893d5bc4306fb70cdaa2',
    messagingSenderId: '585491402759',
    projectId: 'propp-400e1',
    databaseURL: 'https://propp-400e1-default-rtdb.firebaseio.com',
    storageBucket: 'propp-400e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8zTiJI7R1jwCo6G_zt_V4x8NrRIWiFk',
    appId: '1:585491402759:ios:b6f79ee07610696c0cdaa2',
    messagingSenderId: '585491402759',
    projectId: 'propp-400e1',
    databaseURL: 'https://propp-400e1-default-rtdb.firebaseio.com',
    storageBucket: 'propp-400e1.appspot.com',
    iosBundleId: 'com.example.todoAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8zTiJI7R1jwCo6G_zt_V4x8NrRIWiFk',
    appId: '1:585491402759:ios:272883c8f0bfe0c60cdaa2',
    messagingSenderId: '585491402759',
    projectId: 'propp-400e1',
    databaseURL: 'https://propp-400e1-default-rtdb.firebaseio.com',
    storageBucket: 'propp-400e1.appspot.com',
    iosBundleId: 'com.example.todoAssignment.RunnerTests',
  );
}
